version: '3.8'

services:
  database:
    image: postgres:15.5-alpine3.18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test-auth
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d auth']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build:
      dockerfile: Dockerfile
      context: './back'
    container_name: backend
    ports:
      - '4000:4000'
    volumes:
      - ./back:/back
      - ./back/node_modules:/node_modules
    networks:
      - test-auth
      
  client:
    build:
      dockerfile: Dockerfile
      context: './front'
    container_name: client
    volumes:
      - ./front:/front
      - ./front/node_modules:/node_modules
    ports:
      - '3000:3000'
    networks:
      - test-auth

networks:
  test-auth:
    driver: bridge

volumes:
  postgres_data:
    driver: local